-- A manual adjustment to the tax owed, recorded against a date in a tax period: positive adds to the tax
-- owed, negative takes from it. The amount is in the home currency in effect when it was recorded.
CREATE TABLE tax_adjustment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_date DATE NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    reason VARCHAR(200),
    CONSTRAINT tax_adjustment_currency_fk FOREIGN KEY (currency) REFERENCES currency (code),
    CONSTRAINT tax_adjustment_non_zero CHECK (amount <> 0)
);
