-- An invoice is built from line items: a description, how many, and the price of each. The
-- invoice amount is the sum of each line's quantity times unit price, so a draft with no lines yet
-- is worth zero.
CREATE TABLE invoice_line_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT         NOT NULL,
    description VARCHAR(255)   NOT NULL,
    qty         DECIMAL(10, 2) NOT NULL,
    unit_price  DECIMAL(12, 2) NOT NULL,
    CONSTRAINT invoice_line_item_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoice (id),
    CONSTRAINT invoice_line_item_qty_positive CHECK (qty > 0),
    CONSTRAINT invoice_line_item_unit_price_positive CHECK (unit_price > 0)
);

CREATE INDEX invoice_line_item_invoice_idx ON invoice_line_item (invoice_id);

ALTER TABLE invoice DROP CONSTRAINT invoice_amount_positive;
ALTER TABLE invoice ADD CONSTRAINT invoice_amount_not_negative CHECK (amount >= 0);

-- Existing invoices were raised as one figure: carry that figure over as a single line.
INSERT INTO invoice_line_item (invoice_id, description, qty, unit_price)
SELECT id, 'Invoice amount', 1, amount FROM invoice;
