-- A correction to an invoice that has already been sent. Rather than editing the sent invoice, an
-- adjustment note is issued against it: the original amount stays as sent, and the notes (positive to
-- charge more, negative to charge less) give its adjusted total. Each carries the reason for the change.
CREATE TABLE adjustment_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT         NOT NULL,
    amount     DECIMAL(12, 2) NOT NULL,
    reason     VARCHAR(500)   NOT NULL,
    issued_at  TIMESTAMP      NOT NULL,
    CONSTRAINT adjustment_note_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoice (id),
    CONSTRAINT adjustment_note_amount_non_zero CHECK (amount <> 0)
);

CREATE INDEX adjustment_note_invoice_idx ON adjustment_note (invoice_id);
