-- Projects can be labelled with tags so they can be grouped. A tag is a shared label; a project
-- carries any number of them. Tagging belongs to the project and goes with it if it is deleted.
CREATE TABLE tag (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT tag_name_uq UNIQUE (name)
);

CREATE TABLE project_tag (
    project_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    CONSTRAINT project_tag_pk PRIMARY KEY (project_id, tag_id),
    CONSTRAINT project_tag_project_fk FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE,
    CONSTRAINT project_tag_tag_fk FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);

CREATE INDEX project_tag_tag_idx ON project_tag (tag_id);
