-- Free-text notes kept against a record in the app. A note names what it is about by type and id
-- (only projects take notes so far) and is stamped with when it was written so the newest shows
-- first.
CREATE TABLE note (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(20)              NOT NULL,
    target_id   BIGINT                   NOT NULL,
    text        VARCHAR(2000)            NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT note_target_type_ck CHECK (target_type IN ('project'))
);

CREATE INDEX note_target_idx ON note (target_type, target_id, created_at);
