-- Money a client has paid against an invoice: how much and on what day. An invoice can be paid in
-- several instalments; payments are financial records, so they block deleting their invoice.
CREATE TABLE payment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT         NOT NULL,
    amount     DECIMAL(12, 2) NOT NULL,
    paid_date  DATE           NOT NULL,
    CONSTRAINT payment_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoice (id),
    CONSTRAINT payment_amount_positive CHECK (amount > 0)
);

CREATE INDEX payment_invoice_idx ON payment (invoice_id, paid_date);
