-- A lump sum a client pays in one go, split across several of their invoices. Each share is still
-- recorded as an ordinary payment against its invoice, linked back to the lump it came from.
CREATE TABLE client_payment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT         NOT NULL,
    amount    DECIMAL(12, 2) NOT NULL,
    paid_date DATE           NOT NULL,
    CONSTRAINT client_payment_client_fk FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT client_payment_amount_positive CHECK (amount > 0)
);

CREATE INDEX client_payment_client_idx ON client_payment (client_id, paid_date);

ALTER TABLE payment ADD COLUMN client_payment_id BIGINT;
ALTER TABLE payment ADD CONSTRAINT payment_client_payment_fk
    FOREIGN KEY (client_payment_id) REFERENCES client_payment (id);
