CREATE TABLE project (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    client_id BIGINT       NOT NULL,
    CONSTRAINT project_client_fk FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE INDEX project_client_idx ON project (client_id);
