-- An invoice can now carry several discounts at once, each either a percentage or a flat amount off what
-- its line items add up to. Their combined effect comes off before tax: the percentages each take their
-- share of the subtotal, then the flat amounts come off what is left (never more than is left).
CREATE TABLE invoice_discount (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT         NOT NULL,
    discount_pct    DECIMAL(5, 2)  DEFAULT 0 NOT NULL,
    discount_amount DECIMAL(12, 2) DEFAULT 0 NOT NULL,
    CONSTRAINT invoice_discount_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE,
    CONSTRAINT invoice_discount_row_pct_range CHECK (discount_pct >= 0 AND discount_pct <= 100),
    CONSTRAINT invoice_discount_row_amount_non_negative CHECK (discount_amount >= 0),
    CONSTRAINT invoice_discount_row_one_kind CHECK (discount_pct = 0 OR discount_amount = 0),
    CONSTRAINT invoice_discount_row_not_empty CHECK (discount_pct > 0 OR discount_amount > 0)
);

CREATE INDEX invoice_discount_invoice_idx ON invoice_discount (invoice_id);

-- Each invoice's existing discount (only ever one kind) carries over as its single discount, so no
-- amounts change.
INSERT INTO invoice_discount (invoice_id, discount_pct, discount_amount)
SELECT id, discount_pct, discount_amount FROM invoice WHERE discount_pct > 0 OR discount_amount > 0;

ALTER TABLE invoice DROP CONSTRAINT invoice_discount_one_kind;
ALTER TABLE invoice DROP CONSTRAINT invoice_discount_pct_range;
ALTER TABLE invoice DROP CONSTRAINT invoice_discount_amount_non_negative;
ALTER TABLE invoice DROP COLUMN discount_pct;
ALTER TABLE invoice DROP COLUMN discount_amount;
