CREATE TABLE invoice (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT         NOT NULL,
    amount     DECIMAL(12, 2) NOT NULL,
    CONSTRAINT invoice_project_fk FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT invoice_amount_positive CHECK (amount > 0)
);

CREATE INDEX invoice_project_idx ON invoice (project_id);
