-- Money given back to a client against an invoice they were sent. An invoice can carry several
-- credit notes; like payments they are financial records, so they block deleting their invoice.
CREATE TABLE credit_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT         NOT NULL,
    amount     DECIMAL(12, 2) NOT NULL,
    issued_at  TIMESTAMP      NOT NULL,
    CONSTRAINT credit_note_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoice (id),
    CONSTRAINT credit_note_amount_positive CHECK (amount > 0)
);

CREATE INDEX credit_note_invoice_idx ON credit_note (invoice_id);
