-- Money a client pays up front, before any invoice. It is held against the client.
CREATE TABLE deposit (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT         NOT NULL,
    amount    DECIMAL(12, 2) NOT NULL,
    paid_date DATE           NOT NULL,
    CONSTRAINT deposit_client_fk FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT deposit_amount_positive CHECK (amount > 0)
);

CREATE INDEX deposit_client_idx ON deposit (client_id, paid_date);
