-- Part of a client's held deposits put toward their invoices in one go, split the same way as a lump
-- payment. Each share is recorded as an ordinary payment against its invoice, linked back to the
-- application it came from; what is still held is the deposits less everything applied.
CREATE TABLE deposit_application (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT         NOT NULL,
    amount     DECIMAL(12, 2) NOT NULL,
    applied_on DATE           NOT NULL,
    CONSTRAINT deposit_application_client_fk FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT deposit_application_amount_positive CHECK (amount > 0)
);

CREATE INDEX deposit_application_client_idx ON deposit_application (client_id, applied_on);

ALTER TABLE payment ADD COLUMN deposit_application_id BIGINT;
ALTER TABLE payment ADD CONSTRAINT payment_deposit_application_fk
    FOREIGN KEY (deposit_application_id) REFERENCES deposit_application (id);
