-- Unused credit (held deposits and unused credit notes) paid back to a client. A refund draws on
-- the held deposits first and then on unused credit notes; the split is kept so each part of the
-- client's credit drops by exactly what was refunded from it.
CREATE TABLE refund (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         BIGINT         NOT NULL,
    amount            DECIMAL(12, 2) NOT NULL,
    from_deposits     DECIMAL(12, 2) NOT NULL,
    from_credit_notes DECIMAL(12, 2) NOT NULL,
    refunded_on       DATE           NOT NULL,
    note              VARCHAR(500),
    CONSTRAINT refund_client_fk FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT refund_amount_positive CHECK (amount > 0),
    CONSTRAINT refund_split_matches CHECK (from_deposits >= 0 AND from_credit_notes >= 0
        AND from_deposits + from_credit_notes = amount)
);

CREATE INDEX refund_client_idx ON refund (client_id, refunded_on);
