-- The home currency foreign invoices are converted into for the business's own totals; existing data
-- keeps US dollars.
ALTER TABLE app_settings ADD COLUMN home_currency VARCHAR(3) DEFAULT 'USD' NOT NULL;
ALTER TABLE app_settings ADD CONSTRAINT app_settings_home_currency_fk FOREIGN KEY (home_currency) REFERENCES currency (code);

-- Exchange rates by date: one unit of the currency is worth this many units of the home currency from
-- the rate date until the next rate for that currency. An invoice converts at the rate in effect on its
-- issue date.
CREATE TABLE fx_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency VARCHAR(3) NOT NULL,
    rate_date DATE NOT NULL,
    rate DECIMAL(19, 6) NOT NULL,
    CONSTRAINT fx_rate_currency_fk FOREIGN KEY (currency) REFERENCES currency (code),
    CONSTRAINT fx_rate_one_per_day UNIQUE (currency, rate_date),
    CONSTRAINT fx_rate_positive CHECK (rate > 0)
);
