-- A task may carry a checklist of sub-items, each ticked off on its own. They go with their task.
CREATE TABLE task_checklist_item (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT       NOT NULL,
    text    VARCHAR(255) NOT NULL,
    done    BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT task_checklist_item_task_fk FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE
);

CREATE INDEX task_checklist_item_task_idx ON task_checklist_item (task_id);
