-- An invoice can be split into scheduled instalments, each an amount due on a date. They are only
-- a schedule for paying the invoice, not money received, so they go with their invoice.
CREATE TABLE invoice_instalment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT         NOT NULL,
    amount     DECIMAL(12, 2) NOT NULL,
    due_date   DATE           NOT NULL,
    CONSTRAINT invoice_instalment_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE,
    CONSTRAINT invoice_instalment_amount_positive CHECK (amount > 0)
);

CREATE INDEX invoice_instalment_invoice_idx ON invoice_instalment (invoice_id);
