-- An invoice that repeats on a schedule for a fixed amount; the next one falls on next_date.
CREATE TABLE recurring_invoice (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT         NOT NULL,
    amount     DECIMAL(12, 2) NOT NULL,
    frequency  VARCHAR(20)    NOT NULL,
    next_date  DATE           NOT NULL,
    CONSTRAINT recurring_invoice_project_fk FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE,
    CONSTRAINT recurring_invoice_amount_positive CHECK (amount > 0),
    CONSTRAINT recurring_invoice_frequency_known CHECK (frequency IN ('MONTHLY'))
);

CREATE INDEX recurring_invoice_project_idx ON recurring_invoice (project_id, next_date);
