-- A record of each time a client was contacted: when, and a short note of what it was about.
CREATE TABLE contact_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT        NOT NULL,
    contact_date DATE          NOT NULL,
    note         VARCHAR(1000) NOT NULL,
    CONSTRAINT contact_history_client_fk FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE INDEX contact_history_client_idx ON contact_history (client_id, contact_date);
