CREATE TABLE contact (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT       NOT NULL,
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL,
    CONSTRAINT contact_client_fk FOREIGN KEY (client_id) REFERENCES client (id),
    -- Backstop for the API validation, matching the client email rule.
    CONSTRAINT contact_email_format CHECK (email LIKE '_%@_%._%' AND email NOT LIKE '% %')
);

CREATE INDEX contact_client_idx ON contact (client_id);
