-- A note of each time a client's statement was emailed to them: the address it went to and when.
CREATE TABLE statement_email (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT       NOT NULL,
    email     VARCHAR(255) NOT NULL,
    sent_at   TIMESTAMP    NOT NULL,
    CONSTRAINT statement_email_client_fk FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE INDEX statement_email_client_idx ON statement_email (client_id, sent_at);
