CREATE TABLE task (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT       NOT NULL,
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT task_project_fk FOREIGN KEY (project_id) REFERENCES project (id)
);

CREATE INDEX task_project_idx ON task (project_id);
